export const config = {
  MONDAY_API_URL: "https://api.monday.com/v2",
  API_CHECK_GIFT_URL: "/api/check-gift",
  API_SUBMIT_GIFT_URL: "/api/submit-gift",
  API_GIFTS_URL: "/api/gifts",
  MONDAY_API_KEY: process.env.MONDAY_API_KEY,
  USER_BOARD_ID: process.env.MONDAY_USER_BOARD_ID,
  CLAIMS_BOARD_ID: process.env.MONDAY_CLAIMS_BOARD_ID,
  USER_BOARD_USER_ID_COLUMN_ID: process.env.MONDAY_USER_BOARD_USER_ID_COLUMN_ID,
  CLAIMS_BOARD_USER_ID_COLUMN_ID:
    process.env.MONDAY_CLAIMS_BOARD_USER_ID_COLUMN_ID,
  CLAIMS_BOARD_GIFT_TITLE_COLUMN_ID:
    process.env.MONDAY_CLAIMS_BOARD_GIFT_TITLE_COLUMN_ID,
};
