onlyBuiltDependencies:
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
overrides:
  postcss: '>=8.5.23'
  mysql2: '>=3.23.1'
  deepmerge-ts: '>=8.0.0'
  sharp: '>=0.35.4'
